#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import List

import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[1]
import sys

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.metrics import classification_metrics


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Majority-vote ensemble over run_experiment prediction outputs.")
    parser.add_argument(
        "--inputs",
        nargs="+",
        required=True,
        help="List of metrics json files generated by scripts/run_experiment.py",
    )
    parser.add_argument("--output-json", required=True, help="Path to save ensemble metrics json.")
    return parser.parse_args()


def majority_vote(pred_matrix: np.ndarray) -> np.ndarray:
    votes = []
    for row in pred_matrix.T:
        counts = Counter(row.tolist())
        best = sorted(counts.items(), key=lambda item: (-item[1], item[0]))[0][0]
        votes.append(best)
    return np.asarray(votes, dtype=np.int64)


def main() -> int:
    args = parse_args()
    payloads: List[dict] = []
    for path_text in args.inputs:
        path = Path(path_text)
        payloads.append(json.loads(path.read_text(encoding="utf-8")))

    truths = np.asarray(payloads[0]["final_val_truths"], dtype=np.int64)
    preds = [np.asarray(payload["final_val_predictions"], dtype=np.int64) for payload in payloads]

    for index, pred in enumerate(preds):
        if pred.shape != truths.shape:
            raise ValueError(f"Prediction shape mismatch at input {index}: {pred.shape} vs {truths.shape}")

    pred_matrix = np.stack(preds, axis=0)
    voted = majority_vote(pred_matrix)
    metrics = classification_metrics(truths, voted, num_classes=5)

    output = {
        "inputs": [str(Path(path).resolve()) for path in args.inputs],
        "ensemble_size": len(args.inputs),
        "macro_f1": metrics["macro_f1"],
        "accuracy": metrics["accuracy"],
        "kappa": metrics["kappa"],
        "per_class_f1": metrics["per_class_f1"],
        "support": metrics["support"],
        "confusion_matrix": metrics["confusion_matrix"],
    }
    out_path = Path(args.output_json)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(output, indent=2), encoding="utf-8")
    print(json.dumps(output, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
